### ISSUE TITLE
Rounding/significant digit display

### ISSUE THREAD

**Issue by praftery** [CenterForTheBuiltEnvironment/fan-tool#2]
Standardize across all display entities.
2 significant digits? e.g. 

130 fpm, 0.65 m/s
570 fpm, 2.9 m/s
4.4degF

except for dimensions and airflows, which should use 3 significant digits
5 ft, 1.52 m  
2.04 m, 6.69 ft
8110 cfm, 3.83 m3/s

**Comment by dmgt** [comment]
- Rounding to 3 sf showed up as expected on Chrome and Edge, except for Q, which has up to 5 sf in Imperial units, and I'm guessing is intentional to match 3 sf of m3/s. 
- FYI so this can be a known issue, in latest version of Firefox, rounding does not show up as expected
![image](https://user-images.githubusercontent.com/4704963/65918735-3fb27800-e38f-11e9-9864-545db261861f.png)

**Comment by praftery** [comment]
Should be resolved in latest version

**Comment by dmgt** [comment]
Yes, now looks like this in latest version of Firefox: 
![image](https://user-images.githubusercontent.com/4704963/65989699-05a0af00-e43f-11e9-8024-6b212b3ca095.png)

![image](https://user-images.githubusercontent.com/4704963/65989744-16e9bb80-e43f-11e9-9d04-843d2d7a6790.png)
