### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by praftery** [CenterForTheBuiltEnvironment/fan-tool#4]
Link to tool specific documentation at the top of menu
Individual parameters should all ahve tooltips on mouseover, and clickable links to more content (if needed)

**Comment by dmgt** [comment]
Suggestions: 
- Add (eg in User Guide) explanation of the "Save" and "Restore Save" functionality
    - Eg, if a custom fan has been added *and saved* , 'Restore save' will restore it
    - However, saving the page does *not* mean that the same view will be shared with the recipient (recipient will recieve url with same model, but looks like the uppermost layout will be selected by default, regardless of which layout was selected when the model was shared or saved).  
- Add explanation of "Default" candidate fan selection ( currently it appears to deselect all fans)

**Comment by dmgt** [comment]
- Under "Candidate Fan Selection" (eg either as smaller text, or as tool tip), could have text saying that at least one fan model must be selected. 
    - Could also add text saying that "Candidate fan models are anonymized examples of fans commercially available in the US in 2018. To add information for an additional fan model, click "Add".

**Comment by dmgt** [comment]
Additional suggestions/questions from attendees at CBE meeting demo: 

Labels/tooltips/documentation:
- Would be helpful to add mouse over to explain what the delta T is based on. Wasn't necessarily obvious what "Temp increase" meant
- Explain what 'Uniformity' is
- "Are these airspeeds for fans blowing upwards or downwards?"
- Air speed ranges - had questions about other air speeds for reference (eg what is the range of airspeeds at which paper starts to move?) and code compliance (How high is allowed by code, and is that based on the maximum air speed?). 
- "Maximum fan speed" - label a bit unclear, maybe 'fan level - % of maximum fan speed'? 
- "Blade height" - could add '(from floor)', since  "Minimum mount distance" specifies is from ceiling in tooltip, and someone asked about this.
- Adding 'fan level' in table would make it easier to distinguish between same fan at a lower and higher speed (can potentially see this from fpm, but fpm varies by fan)

Scope:
- Someone asked if can also be used for residential spaces, or if there are existing resources to refer to for those?
- Someone asked what about cathedral (vaulted) roof?
